### ISSUE TITLE
购票流程

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/devcon#1]
## 页面和流程

- [ ] 如果买过票，弹出错误提示，跳转到个人中心页面
	- 问题：可以同时买两种票么？暂定为可以
- [x] 票种展示和选择页面，可以参考：
	- https://material-ui.com/getting-started/templates/pricing/
	- https://react-material-kit.devias.io/pricing
	- 页面上除了展示票种，最好也展示活动时间、活动内容
- [x] 选择票种之后，进入支付（免费票需要签个随机串），弹出 DID-Auth 流程
	- 免费票和收费票是按两种规则来生成的，单个 DID 只可能生成1个，意味着只能买1次
	- 免费票和收费票都是 NFT 和 VC，里面的数据不同
	- 票都是预先创建的，Owner 是 dApp，然后走到某个流程转给购票者
- [ ] 个人中心页面：DID-Auth 流程结束之后跳转到这里
	- 展示已购 Tickets
	- 展示 Certificates？【低优先级】

## 数据结构

生成的 Ticket 都属于 NFTTicket 类型。

### 免费票

```js
{
	type: 'DevCon2020FreeTicket',
	name: 'ArcBlock DevCon2020 Ticket (Free)',
	description: 'Passport to ArcBlock DevCon2020 Day1 Online sessions',
	location: 'Online',
	startTime: 'UTC 2020-06-19 00:00:00',
	endTime: 'UTC 2020-06-19 23:59:59',
	display: '先用标准的 ticket display',
	issuer: '这里使用 dapp 的 did，名称命名为 devcon2020 就好了',
}
```

### 收费票

```js
{
	type: 'DevCon2020PaidTicket',
	name: 'ArcBlock DevCon2020 Ticket (Pro)',
	description: 'Passport to ArcBlock DevCon2020 Day1 Online sessions and Day2 workshops',
	location: 'Online',
	startTime: 'UTC 2020-06-19 00:00:00',
	endTime: 'UTC 2020-06-20 23:59:59',
	display: '先用标准的 ticket display',
	issuer: '这里使用 dapp 的 did，名称命名为 devcon2020 就好了',
}
```

**Comment by NateRobinson** [comment]
> > 问题：可以同时买两种票么?
> 
> 可以，不必要限制。
> 
> > 免费票和收费票是按两种规则来生成的，单个 DID 只可能生成1个，意味着只能买1次
> 
> 我认为没必要限制，简化问题，而且票是可以转让，赠送的。 不做限制反而更灵活（例如我可以买很多张票送给别人）

如果可以送给别人，并且收到的人也要能用的话，我们就不能通过 vc verify的方式来检查了，只能通过去链上看是否持有 NFT。
