### ISSUE TITLE
devcon repo itself open source and have a GitHub link

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/devcon#16]
devcon repo itself open source and have a GitHub link.   we can use devcon app as an example how to use Arcblock, xmark etc. to develop event site like this

**Comment by robroyhobbs** [comment]
@mave99a is this where users will go to register, pull request, etc?  Can I use this URL in the hackathon page as the starting point to participate?

**Comment by mave99a** [comment]
no. hackathon should be a separate Skelton repo.  

open source this conference app is just for demonstrate this kind of application.

**Comment by robroyhobbs** [comment]
Got it. thanks. ;) @wangshijun just let me know where the repo is that we should direct people to and also what the possible URLs are for reference materials and documentation that we will open up.
