### ISSUE TITLE
arcblock logo in front of devcon

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/devcon#18]
put an logo in front of devcon

**Comment by wangshijun** [comment]
Let's use arcblock logo

**Comment by robroyhobbs** [comment]
@wangshijun this was the same issue from the I did it page as well.  agree just having arcblock logo is sufficient since devcon mentioned throughout.  I mention this as I would like to have this as the default for new microsites that we create so we can build these customer small sites ;)

**Comment by wangshijun** [comment]
@robroyhobbs ok

**Comment by Jeanchen27** [comment]
@NateRobinson Could you fix this problem?

**Comment by NateRobinson** [comment]
Fixed in #38
