### ISSUE TITLE
验票和参与 Session/Workshop 的流程

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/devcon#2]
## 基本页面和流程

> 问题1：Day1 的所有 Session 都用相同的房间链接？还是每个 Session 有自己的房间链接？
> 问题2：参与的时候链接露出需要通过钱包么？

- [x] 打开 Schedule 页面，找到感兴趣的 Session，点击进入，跳转到另外1个 JS 控制的页面
	- 传递的参数是某个 session 的 slug，后端会根据 slug 去查找这个房间链接、直播链接
- [x] 跳转到的 JS 页面要求先验票：验票通过后：
	- [ ] 如果 Session 正在进行中，验票之后展示房间链接
	- [ ] 如果 Session 已经结束，验票之后展示录播链接：Youtube

### Session 和 Workshop 对应的房间链接

需要把 Session 和 Workshop 对应的房间链接以配置的形式保存到 Repo 里面，比如下面的格式：

```js
[
	{
		type: 'session',
		id: 'arcblock-platform-recap',
		startTime: 'UTC 时间',
		endTime: 'UTC 时间',
		streamLink: '直播地址',
		videoLink: '录播地址',
	},
	{
		type: 'workshop',
		id: 'up-and-running-with-abtnode',
		startTime: 'UTC 时间',
		endTime: 'UTC 时间',
		streamLink: '直播地址',
		videoLink: '录播地址',
	},
]
```

### 验票时给钱包的筛选条件

- trustedIssuers：devcon app 的 did
- type：DevCon2020FreeTicket, DevCon2020PaidTicket

**Comment by NateRobinson** [comment]
#27
