### ISSUE TITLE
conference schedule table CSS reference

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/devcon#25]
I found this one: 

https://codepen.io/holopez/pen/bGbmLQa

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/41923/83211032-ec0c5000-a110-11ea-9917-ed77d67d88c3.png">

**Comment by robroyhobbs** [comment]
Yeah, agree. I also see this design a lot but maybe for the next round.  https://www.mongodb.com/world/sessions.  @NateRobinson is that difficult to implement?  Also, make sure we note the table formatting as it will apply to the pricing page too.

**Comment by mave99a** [comment]
I think the date on current pages can be removed, since it's all the same date

**Comment by robroyhobbs** [comment]
submitted update to remove date from left hand column.
