### ISSUE TITLE
Should we merge "workshop" and "Schedule"

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/devcon#26]
Since they are essentially just different category

**Comment by robroyhobbs** [comment]
Yeah, i think it would be easier and I was thinking of the workshops as separate "training" courses or sessions to prepare before/after the event and for the hackathon.

**Comment by Jeanchen27** [comment]
According to my discussion with Matt today, we hide workshop at first and make it exclusive for paid users.

**Comment by NateRobinson** [comment]
#33 will hide workshop by this PR, and will add show workshop by  user's tickets.
