### ISSUE TITLE
关于门票作用的讨论

### ISSUE THREAD

**Issue by NateRobinson** [ArcBlock/devcon#31]
起初的设想，收费门票和免费门票是有一个作用是**限制用户能否参加第二天的活动**，但是在实现过程中，发现因为我们的视频，直播都是放在一个第三方平台的，所以没法限制用户能不能观看（比如有人在群里分享了视频链接这种情况）

换个方向，是否这个门票可以用来限制用户能否领我们的纪念徽章（证书），因为这个是我们网站可以控制的。下面是几种 case：

1. 没有任何门票的，或者未登录的--》无法领取纪念徽章（证书）
2. 有免费票的--》可以领取部分纪念徽章（证书）
3. 有收费票的--》可以领取全部纪念徽章（证书）

**Comment by mave99a** [comment]
不做内容的限制，主要还是让用户体验一下。 

另外门票主要作用是用来获得徽章，或者获得独特的内容。 例如我们可以把演讲的pdf等放在专门的区域，有票的才能下载

**Comment by Jeanchen27** [comment]
- 免费和付费门票都可以观看直播和视频；
- 付费门票的专有权益包含：
   - 独有的纪念徽章；
   - 演讲胶片PDF专区下载；
   - 新书签名版（等于一个预约码，出书后寄送）；
   - 其他（欢迎大家补充）。

**Comment by Jeanchen27** [comment]
100 ABT 照现在价格，只能买一本书的样子:P
>   * 新书签名版（等于一个预约码，出书后寄送）；
