### ISSUE TITLE
Polish Speakers Page

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/devcon#5]
Add more item to the speakers page, maybe we need to split speakers to English/Chinese Track?

**Comment by mave99a** [comment]
we put speakers together on same page, it will appear that we have many speakers.

**Comment by robroyhobbs** [comment]
yep, agree.  I suggested we create one format and just adjust the language text depending on which.  @Jeanchen27 can you begin adding CH additions ? I am thinking we can put a placeholder icon for people where we don't currently have a picture or they don't send us one.

**Comment by robroyhobbs** [comment]
i added arcblock icon as a placeholder so the list shows correctly now.

**Comment by robroyhobbs** [comment]
english speakers added. @Jeanchen27 can you add CH speakers as well?

**Comment by Jeanchen27** [comment]
We can add speakers and update this page from time to time.
