### ISSUE TITLE
登录后，第一次来这个页面这个体验有点不好

### ISSUE THREAD

**Issue by mave99a** [ArcBlock/devcon#58]
<img width="671" alt="image" src="https://user-images.githubusercontent.com/41923/83937793-b73d7000-a784-11ea-8f5d-4db126153445.png">

一秒后变成loading，然后出现票。  

可以上来先spin一下，确定了login状态再显示要用户login，还是loading票

**Comment by NateRobinson** [comment]
我也发现了这个问题，已优化。
