### ISSUE TITLE
Update Schedule Page

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/devcon#6]
We need to nail down the following details about session speaker and workshop host:

- topic: we need a good title
- speaker: name, title, social links?
- start time
- end time

https://docs.google.com/spreadsheets/d/1ZT95lNW8JvSFX2wuuBFCBroRbmZrRnPNnLF9oPyQUdM/edit#gid=0

**Comment by Jeanchen27** [comment]
DONE
